#ifndef UPLOAD_CLIENT_DTP_SERVER_H
#define UPLOAD_CLIENT_DTP_SERVER_H

#define INDECES_PACKET_SIZE 196
#define INDECES_PORT 10

#define UPLOAD_CLIENT_DTP_UPLOAD_REQUEST 0
#define UPLOAD_CLIENT_DTP_RESUME_REQUEST 1
#define UPLOAD_CLIENT_DTP_STATUS_REQUEST 2

#endif